# Telco Customer Churn Prediction

## Project Objective
The goal of this project is to predict whether a telecom customer is likely to leave (churn) using machine learning.

## Dataset
- Telco Customer Churn Dataset
- Total Records: 7043
- Features: Customer demographics, services, billing, and contract information

## Technologies Used
- Python
- Pandas
- NumPy
- Scikit-learn
- Google Colab

## Machine Learning Algorithm
- Random Forest Classifier

## Model Performance
- Accuracy: 95%

## Project Workflow
1. Import libraries
2. Load dataset
3. Explore the data
4. Handle missing values
5. Encode categorical variables
6. Split data into training and testing sets
7. Train the Random Forest model
8. Make predictions
9. Evaluate model performance

In [ ]:
#CONNECT GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#IMPORT REUIRED TO LIBRARYS
import numpy as np
import pandas as pd

In [ ]:
# Import library for data visualization
import matplotlib.pyplot as plt

In [ ]:
# Import the Random Forest machine learning algorithm
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Load the Telco Customer Churn dataset
df=pd.read_csv('/content/drive/MyDrive/Saved from Chrome/telco.csv')

In [ ]:
# Display the first 5 rows of the dataset
df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

In [ ]:
# Display dataset information such as columns, data types, and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   object
 4   Senior Citizen                     7043 non-null   object
 5   Married                            7043 non-null   object
 6   Dependents                         7043 non-null   object
 7   Number of Dependents               7043 non-null   int64
 8   Country                            7043 non-null   object
 9   State                              7043 non-null   object
 10  City                               7043 non-null   object
 11  Zip Code                           7043 non-null   int64
 12  Latitude                           7043 non-null   float64
 13  Longitude                          7043 non-null   float64
 14  Population                         7043 non-null   int64
 15  Quarter                            7043 non-null   object
 16  Referred a Friend                  7043 non-null   object
 17  Number of Referrals                7043 non-null   int64
 18  Tenure in Months                   7043 non-null   int64
 19  Offer                              3166 non-null   object
 20  Phone Service                      7043 non-null   object
 21  Avg Monthly Long Distance Charges  7043 non-null   float64
 22  Multiple Lines                     7043 non-null   object
 23  Internet Service                   7043 non-null   object
 24  Internet Type                      5517 non-null   object
 25  Avg Monthly GB Download            7043 non-null   int64
 26  Online Security                    7043 non-null   object
 27  Online Backup                      7043 non-null   object
 28  Device Protection Plan             7043 non-null   object
 29  Premium Tech Support               7043 non-null   object
 30  Streaming TV                       7043 non-null   object
 31  Streaming Movies                   7043 non-null   object
 32  Streaming Music                    7043 non-null   object
 33  Unlimited Data                     7043 non-null   object
 34  Contract                           7043 non-null   object
 35  Paperless Billing                  7043 non-null   object
 36  Payment Method                     7043 non-null   object
 37  Monthly Charge                     7043 non-null   float64
 38  Total Charges                      7043 non-null   float64
 39  Total Refunds                      7043 non-null   float64
 40  Total Extra Data Charges           7043 non-null   int64
 41  Total Long Distance Charges        7043 non-null   float64
 42  Total Revenue                      7043 non-null   float64
 43  Satisfaction Score                 7043 non-null   int64
 44  Customer Status                    7043 non-null   object
 45  Churn Label                        7043 non-null   object
 46  Churn Score                        7043 non-null   int64
 47  CLTV                               7043 non-null   int64
 48  Churn Category                     1869 non-null   object
 49  Churn Reason                       1869 non-null   object
dtypes: float64(8), int64(11), object(31)
memory usage: 2.7+ MB

In [ ]:
# check missing values
df.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Population                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Score                             0
CLTV                                    0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [ ]:
# Display dataset columns
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Under 30', 'Senior Citizen', 'Married',
       'Dependents', 'Number of Dependents', 'Country', 'State', 'City',
       'Zip Code', 'Latitude', 'Longitude', 'Population', 'Quarter',
       'Referred a Friend', 'Number of Referrals', 'Tenure in Months', 'Offer',
       'Phone Service', 'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Satisfaction Score', 'Customer Status', 'Churn Label',
       'Churn Score', 'CLTV', 'Churn Category', 'Churn Reason'],
      dtype='object')

In [ ]:
# Remove unnessary columns
df.drop(
    columns=[
        "Customer ID",
        "Churn Score",
        "Customer Status",
        "Churn Category",
        "Churn Reason"
    ],
    inplace=True
)

In [ ]:
# Fill missing values in the 'Offer' column with 'No Offer'
df['Offer']=df['Offer'].fillna('No Offer')

In [ ]:
# Fill missing values in the 'Internet type' column with 'No internet service'
df['Internet Type']=df['Internet Type'].fillna('No Internet Service')

In [ ]:
# convert all catogorical(TEXT) columns into numerical values using Label encoder
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for column in df.columns:
  if df[column].dtype=='object':
    df[column]=encoder.fit_transform(df[column])

In [ ]:
# Check the data set columns Data Types
df.dtypes

Gender                                 int64
Age                                    int64
Under 30                               int64
Senior Citizen                         int64
Married                                int64
Dependents                             int64
Number of Dependents                   int64
Country                                int64
State                                  int64
City                                   int64
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Population                             int64
Quarter                                int64
Referred a Friend                      int64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                  int64
Phone Service                          int64
Avg Monthly Long Distance Charges    float64
Multiple Lines                         int64
Internet Service                       int64
Internet Type                          int64
Avg Monthly GB Download                int64
Online Security                        int64
Online Backup                          int64
Device Protection Plan                 int64
Premium Tech Support                   int64
Streaming TV                           int64
Streaming Movies                       int64
Streaming Music                        int64
Unlimited Data                         int64
Contract                               int64
Paperless Billing                      int64
Payment Method                         int64
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Satisfaction Score                     int64
Churn Label                            int64
CLTV                                   int64
dtype: object

In [ ]:
# Create the feature matrix (X) by removing the target column
x = df.drop('Churn Label', axis=1)

# Create the target variable (y) containing the customer churn labels
y = df['Churn Label']

In [ ]:
# Display the number of rows and columns in the feature dataset
print(x.shape)

(7043, 44)

In [ ]:
# Display the number of values in the target variable
print(y.shape)

(7043,)

In [ ]:
# Display the first 5 rows in feature dataset
x.head()

,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,City,...,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,CLTV
0,1,78,0,1,0,0,0,0,0,554,...,1,0,39.65,39.65,0.00,20,0.00,59.65,3,5433
1,0,74,0,1,1,1,1,0,0,554,...,1,1,80.65,633.30,0.00,0,390.80,1024.10,3,5302
2,1,71,0,1,0,1,3,0,0,554,...,1,0,95.45,1752.55,45.61,0,203.94,1910.88,2,3179
3,0,78,0,1,1,1,1,0,0,448,...,1,0,98.50,2514.50,13.43,0,494.00,2995.07,2,5337
4,0,80,0,1,1,1,1,0,0,1072,...,1,0,76.50,2868.15,0.00,0,234.21,3102.36,2,2793

In [ ]:
# Display the firt 5 values of target variable
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Churn Label, dtype: int64

In [ ]:
# split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
#display the shape of traiing and testing datasets
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5634, 44)
(1409, 44)
(5634,)
(1409,)

In [ ]:
# Train the RandonForestClassifier Model
model = RandomForestClassifier(random_state=42)

model.fit(x_train, y_train)

print("Model training completed!")

Model training completed!

In [ ]:
#predict costomer churn using test dataset
y_pred = model.predict(x_test)
print(y_pred)

[0 0 0 ... 1 0 0]

In [ ]:
#Calculate accuracy of trained model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print('Accuracy:',accuracy)

Accuracy: 0.9531582682753726

In [ ]:
#Display the confusion matrix to evaluate model
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1004    5]
 [  61  339]]

In [ ]:
#display the classification report of the model
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1009
           1       0.99      0.85      0.91       400

    accuracy                           0.95      1409
   macro avg       0.96      0.92      0.94      1409
weighted avg       0.95      0.95      0.95      1409